### ISSUE TITLE
More guidance on using eclipse debugging features

### ISSUE THREAD

**Issue by jrgnicho** [ethz-asl/eclipsify#34]
It might be good measure to add links to informational posts such [as this](https://www.ceh-photo.de/blog/?p=899) or write out instructions for leveraging the debugging tools available within eclipse.  I tested the instructions provided on that link and eclipse did indeed connected to my ROS node and allowed stepping through the code and do other debugging related tasks, although it had issues connecting to running nodes at times.

**Comment by jrgnicho** [comment]
I have a short tutorial on [debugging ros applications with eclipse](https://github.com/jrgnicho/ros_development_config/blob/xenial/gdb/README.md), if there's any interest I can initiate a PR that adds these instructions to this repo

**Comment by HannesSommer** [comment]
@jrgnicho  thanks a lot for your offer. I believe adding a link to your tutorial would be a easier to maintain and also a bit cleaner since it is more specific as the scope of eclipsify.  I've added such a link to the README. Do you like this solution?

**Comment by jrgnicho** [comment]
@HannesSommer yes I'm good with having a link, I'll just have to remember not to change the directory structure of my repo.  Thank you
